OpenErpTest/OpenERP/OpenERP.Web/Controllers/DeliveryController.cs
using System.Web.Mvc;

namespace OpenERP.Web.Controllers
{
    using OpenERP.Web.Models;

    public class DeliveryController : BaseController
    {
        public ActionResult Index(string number)
        {
            var model = new DeliveryViewModel { Number = number };

            this.RunSafe(
                () =>
                    {
                        if (!string.IsNullOrWhiteSpace(model.Number))
                        {
                            model.Invoice = (new WCF.Invoice.InvoiceClient()).GetByNumber(number);
                        }
                    });
            

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(DeliveryViewModel model)
        {
            this.RunSafe(
                () =>
                    {
                        if (!string.IsNullOrWhiteSpace(model.Number))
                        {
                            model.Invoice = (new WCF.Invoice.InvoiceClient()).GetByNumber(model.Number);
                        }
                    });
            return View(model);
        }

        [HttpPost]
        public ActionResult Deliver(DeliveryViewModel model)
        {
            this.RunSafe(
                () =>
                    {
                        if (!string.IsNullOrWhiteSpace(model.Number))
                        {
                            model.Invoice = (new WCF.Invoice.InvoiceClient()).GetByNumber(model.Number);
                        }

                        (new WCF.Delivery.DeliveryClient()).Add(model.Invoice.Id, model.DeliveryQuantity);
                        model.Invoice = (new WCF.Invoice.InvoiceClient()).GetByNumber(model.Number);
                    });
            return this.View("Index", model);
        }
    }
}

OpenErpTest/OpenERP/OpenERP.Web/Controllers/InvoiceController.cs
namespace OpenERP.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper;

    using OpenERP.Web.Models;
    using OpenERP.Web.WCF.Invoice;
    using OpenERP.Web.WCF.Product;
    using OpenERP.Web.WCF.Customer;

    public class InvoiceController : BaseController
    {
        private readonly CustomerClient customerService = new CustomerClient();
        private readonly ProductClient productService = new ProductClient();

        public ActionResult Index()
        {
            return View(new InvoiceSearchViewModel
            {
                CustomerName = "ryhm372",
                ProductName = "ryhm372"
            });
        }

        [HttpPost]
        public ActionResult Index(InvoiceSearchViewModel model)
        {
            this.RunSafe(() =>
            {
                if (!string.IsNullOrWhiteSpace(model.CustomerName))
                {
                    model.Customer = customerService.Search(model.CustomerName).First();
                }

                if (!string.IsNullOrWhiteSpace(model.ProductName))
                {
                    model.Products = productService.SearchByName(model.ProductName).ToList();
                }
            });

            return this.View(model);
        }

        [HttpPost]
        public ActionResult Create(InvoiceCreateViewModel model)
        {
            model = this.UpdateCreateViewModel(model);

            if (model.SubTask != "create-invoice")
            {
                return this.View(model);
            }

            var client = new InvoiceClient();
            var invoice = client.Create(
                Mapper.Map<WCF.Invoice.Customer>(model.Customer),
                Mapper.Map<WCF.Invoice.ProductProduct>(model.Product),
                model.Amount);


            return RedirectToAction("Created", new { id = invoice.Id });
        }

        public ActionResult Created(int id)
        {
            var client = new InvoiceClient();
            var invoice = client.GetById(id);

            return this.View("Created", invoice);

        }

        private InvoiceCreateViewModel UpdateCreateViewModel(InvoiceCreateViewModel model)
        {
            model.Customer = this.customerService.SearchById(model.CustomerId);
            model.Product = this.productService.SearchById(model.ProductId);

            if (model.Amount <= 0)
            {
                model.Amount = 0;
            }

            if (model.Amount > 0 && model.Product.LstPrice.HasValue)
            {
                model.TotalAmount = model.Product.LstPrice.Value * model.Amount;
            }

            return model;
        }
    }
}

OpenErpTest/OpenERP/OpenERP.Web/Controllers/PaymentController.cs
using System.Web.Mvc;

namespace OpenERP.Web.Controllers
{
    using OpenERP.Web.Models;
    using OpenERP.Web.WCF.Invoice;
    using OpenERP.Web.WCF.Payment;

    public class PaymentController : BaseController
    {
        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult Add(string number)
        {
            AccountInvoice invoice = null;

            this.RunSafe(() => invoice = (new InvoiceClient()).GetByNumber(number));
            
            return this.View(invoice);
        }

        [HttpPost]
        public ActionResult Add(string number, string amount)
        {
            AccountInvoice invoice = null;
            
            this.RunSafe(
                () =>
                    {
                        invoice = (new InvoiceClient()).GetByNumber(number);

                        var dAmount = double.Parse(amount);

                        var paymentService = new PaymentClient();
                        paymentService.Add(invoice.Id, dAmount);

                        invoice = (new InvoiceClient()).GetByNumber(number);
                    });
            

            return this.View(invoice);
        }
    }
}

OpenErpTest/OpenERP/OpenERP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IDU0080</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Müügisüsteem", "Index", "Invoice", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Arvete tegemine", "Index", "Invoice")</li>
                    <li>@Html.ActionLink("Maksmine", "Index", "Payment")</li>
                    <li>@Html.ActionLink("Kauba kätteandmine", "Index", "Delivery")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>